name: Send Recipe Notification

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  send-recipe:
    environment: production
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - run: npm install

      - name: Run script
        env:
          FIREBASE_SERVICE_ACCOUNT_JSON: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}
        run: node sendRecipe.js

      - name: Check secret
        run: |
          if [ -z "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" ]; then
            echo "❌ Secret NOT available"
          else
            echo "✅ Secret available"
          fi
